version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 10
    directory: /action
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
