blank_issues_enabled: false
contact_links:
  - name: ğŸ“¦ Core issue submit
    url: https://github.com/uNetworking/uWebSockets.js/issues
    about: Link to issues of framework which nanoexpress built on top ğŸ’ª
  - name: ğŸ“ Documentation
    url: https://github.com/nanoexpress/docs/issues
    about: Issue for documentations should be created here ğŸ—’
  - name: ğŸ”— Middlewares
    url: https://github.com/nanoexpress/middlewares/issues
    about: Issue for middlewares should be created here ğŸ–‡
  - name: ğŸ™Œ Help
    url: https://stackoverflow.com/questions/tagged/nanoexpress
    about: Any help or issues like cannot run example should be posted here ğŸ¤—
  - name: ğŸ†• Updates channel
    url: https://t.me/nanoexpress
    about: Updates channel ğŸ¤«
  - name: ğŸ’¬ Discussion
    url: https://t.me/nanoexpress_discussion
    about: Discussion chat ğŸ™‹â€â™‚ï¸
  - name: ğŸ›  Dedicated support
    url: https://t.me/dalisoft
    about: Dedicated premium support from author ğŸ’°
